import { Task, Achievement, User, LeaderboardEntry } from './types';

export const initialUser: User = {
  name: 'Алексей',
  avatar: '🧙‍♂️',
  level: 7,
  xp: 340,
  xpToNextLevel: 500,
  totalXp: 3400,
  streak: 12,
  longestStreak: 21,
  lastActiveDate: new Date().toISOString().split('T')[0],
  tasksCompleted: 156,
  joinDate: '2024-09-15',
};

export const initialTasks: Task[] = [
  {
    id: '1',
    title: 'Утренняя зарядка',
    description: '20 минут упражнений каждое утро',
    type: 'recurring',
    priority: 'high',
    category: 'health',
    xpReward: 30,
    completed: false,
    createdAt: '2024-11-01',
    streakCount: 12,
    lastCompleted: '2024-12-19',
  },
  {
    id: '2',
    title: 'Прочитать 30 страниц',
    description: 'Читать книгу по саморазвитию',
    type: 'recurring',
    priority: 'medium',
    category: 'learning',
    xpReward: 25,
    completed: true,
    createdAt: '2024-11-05',
    streakCount: 8,
    lastCompleted: new Date().toISOString().split('T')[0],
  },
  {
    id: '3',
    title: 'Закончить проект на работе',
    description: 'Завершить квартальный отчёт',
    type: 'single',
    priority: 'high',
    category: 'work',
    xpReward: 100,
    completed: false,
    createdAt: '2024-12-10',
    dueDate: '2024-12-25',
  },
  {
    id: '4',
    title: 'Выучить 1000 слов на английском',
    description: 'Расширить словарный запас',
    type: 'longterm',
    priority: 'medium',
    category: 'learning',
    xpReward: 500,
    completed: false,
    createdAt: '2024-10-01',
    progress: 67,
    targetValue: 1000,
    currentValue: 670,
  },
  {
    id: '5',
    title: 'Медитация',
    description: '10 минут медитации перед сном',
    type: 'recurring',
    priority: 'low',
    category: 'health',
    xpReward: 15,
    completed: true,
    createdAt: '2024-11-15',
    streakCount: 5,
    lastCompleted: new Date().toISOString().split('T')[0],
  },
  {
    id: '6',
    title: 'Написать статью в блог',
    description: 'Опубликовать пост о продуктивности',
    type: 'single',
    priority: 'low',
    category: 'creative',
    xpReward: 50,
    completed: false,
    createdAt: '2024-12-18',
    dueDate: '2024-12-30',
  },
];

export const initialAchievements: Achievement[] = [
  {
    id: '1',
    title: 'Первый шаг',
    description: 'Выполните свою первую задачу',
    icon: '🌱',
    unlocked: true,
    unlockedAt: '2024-09-16',
    condition: 'first_task',
    xpReward: 50,
  },
  {
    id: '2',
    title: 'Неделя силы',
    description: 'Серия из 7 дней без пропусков',
    icon: '🔥',
    unlocked: true,
    unlockedAt: '2024-09-23',
    condition: 'streak_7',
    xpReward: 100,
  },
  {
    id: '3',
    title: 'Сотня побед',
    description: 'Выполните 100 задач',
    icon: '💯',
    unlocked: true,
    unlockedAt: '2024-11-20',
    condition: 'tasks_100',
    xpReward: 200,
  },
  {
    id: '4',
    title: 'Марафонец',
    description: 'Серия из 30 дней без пропусков',
    icon: '🏃',
    unlocked: false,
    condition: 'streak_30',
    xpReward: 500,
  },
  {
    id: '5',
    title: 'Тысячник',
    description: 'Наберите 1000 очков опыта',
    icon: '⭐',
    unlocked: true,
    unlockedAt: '2024-10-05',
    condition: 'xp_1000',
    xpReward: 100,
  },
  {
    id: '6',
    title: 'Мастер привычек',
    description: 'Создайте 5 повторяющихся задач',
    icon: '🔄',
    unlocked: true,
    unlockedAt: '2024-10-15',
    condition: 'recurring_5',
    xpReward: 150,
  },
  {
    id: '7',
    title: 'Легенда',
    description: 'Достигните 10 уровня',
    icon: '👑',
    unlocked: false,
    condition: 'level_10',
    xpReward: 1000,
  },
  {
    id: '8',
    title: 'Ранняя пташка',
    description: 'Выполните задачу до 7 утра 5 раз',
    icon: '🌅',
    unlocked: false,
    condition: 'early_bird_5',
    xpReward: 200,
  },
  {
    id: '9',
    title: 'Полтысячи',
    description: 'Выполните 500 задач',
    icon: '🏆',
    unlocked: false,
    condition: 'tasks_500',
    xpReward: 500,
  },
  {
    id: '10',
    title: 'Неделя здоровья',
    description: '7 дней подряд выполняйте задачи из категории "Здоровье"',
    icon: '💪',
    unlocked: true,
    unlockedAt: '2024-11-01',
    condition: 'health_streak_7',
    xpReward: 150,
  },
];

export const leaderboardData: LeaderboardEntry[] = [
  { id: '1', name: 'Мария К.', avatar: '🧝‍♀️', level: 15, xp: 7500, tasksCompleted: 342, streak: 45 },
  { id: '2', name: 'Дмитрий П.', avatar: '🦸‍♂️', level: 12, xp: 5800, tasksCompleted: 278, streak: 33 },
  { id: '3', name: 'Алексей', avatar: '🧙‍♂️', level: 7, xp: 3400, tasksCompleted: 156, streak: 12 },
  { id: '4', name: 'Ольга С.', avatar: '🧚‍♀️', level: 9, xp: 4200, tasksCompleted: 198, streak: 28 },
  { id: '5', name: 'Иван Р.', avatar: '🦹‍♂️', level: 6, xp: 2900, tasksCompleted: 134, streak: 8 },
  { id: '6', name: 'Анна В.', avatar: '👸', level: 11, xp: 5100, tasksCompleted: 245, streak: 19 },
  { id: '7', name: 'Сергей М.', avatar: '🤴', level: 8, xp: 3800, tasksCompleted: 167, streak: 15 },
  { id: '8', name: 'Елена Т.', avatar: '🧙‍♀️', level: 5, xp: 2300, tasksCompleted: 112, streak: 6 },
];
